### PR TITLE
Fix launch config source lookup error

### PR DESCRIPTION
**Pull request by sdruskat**
## Pull request type

 

IDE setup fix

## What is the current behavior?

On some platforms (namely mine and @bunz-lightyear's), Hexatomic in the current develop branch doesn't start from Eclipse, giving the error `Unable to restore source lookup path - unknown type source container type specified: org.eclipse.cdt.debug.core.containerType.project`.

## What is the new behavior?

- Removes source lookup-related lines from launch config
- Adds lines that have been automatically added after removing and recovering launch config
- Runs fine from Eclipse now

## Does this introduce a breaking change?

No.

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [x] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [x] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [x] Build (`mvn verify`) was run locally and any changes were pushed
- [x] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [x] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

### CODE REVIEW

**Comment by sdruskat** [comment]
This may actually need more work, as the source lookup is related to embedded Pepper plugins.

**Comment by sdruskat** [comment]
> This may actually need more work, as the source lookup is related to embedded Pepper plugins.

Tested running import from Hexatomic started from Eclipse, and it works just fine, so this should be good after all.
@thomaskrause & @bunz-lightyear please test locally!

Also, please check if this may resolve the issues that #270 attempts to fix.

I guess this has been caused by an artifactual commit from the import/export development stream...

**Review by bunz-lightyear — COMMENTED** [review]
For me it solved the problem. 👍

**Review by thomaskrause — APPROVED** [review]
Works for me too. Thanks for fixing this!

**Pull request merged**
