### PR TITLE
Document continuous integration

### LINKED ISSUE #84: Add GitHub Actions docs to maintenance documentation
Add a section on how to work with Travis in the maintenance docs.

### PR DESCRIPTION
**Pull request by sdruskat**
## Pull request type

 
- Documentation content changes

## What is the current behavior?

Use of continuous integration isn't documented.

Issue Number: #84

## What is the new behavior?

- [x] Add a section to the *maintenance* section of the user documentation, documenting the use of CI with GitHub Actions
- [x] Add a subsection documenting the use of SonarCloud for static code analysis and reporting
- [x] Fix #84 

## Does this introduce a breaking change?

No

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [x] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [x] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [x] Build (`mvn verify`) was run locally and any changes were pushed
- [x] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [x] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

### CODE REVIEW

**Comment by sdruskat** [comment]
@thomaskrause Ready to review, but CI fails due to inability to install some packages needed for metacity. Perhaps try again later.

```bash
Err:47 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libjavascriptcoregtk-4.0-18 amd64 2.30.5-0ubuntu0.20.04.1
  404  Not Found [IP: 52.147.219.192 80]
Err:56 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libwebkit2gtk-4.0-37 amd64 2.30.5-0ubuntu0.20.04.1
  404  Not Found [IP: 52.147.219.192 80]
Fetched 9162 kB in 0s (23.3 MB/s)
Error: Process completed with exit code 100.
```

**Review by thomaskrause — COMMENTED** [review]
I think the documentation of what the CI is for, where the files are located and which Jobs we have (including the description of SonarCloud) are good.

But I am hesitant to have detailed step-by-step documentation for each job in the generic developer documentation. I think this kind of documentation is best located as inline-comment in the actual workflow files, like we do with the build-related shell scripts. Keeping this documentation in sync will probably fail.

**Comment by sdruskat** [comment]
> But I am hesitant to have detailed step-by-step documentation for each job in the generic developer documentation. I think this kind of documentation is best located as inline-comment in the actual workflow files, like we do with the build-related shell scripts. Keeping this documentation in sync will probably fail.
> 
> P.S. I think this is also in contradiction to the new "howto document" documentation, where it clearly says "Documentation should be put as closely as possible to the thing it describes." in the "Document where it makes the most sense". section

You're right. Removed step descriptions in https://github.com/hexatomic/hexatomic/pull/296/commits/0b08826c21d5d41c8aceeb9cffb2deb384cdaba4.

**Review by thomaskrause — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
