### PR TITLE
#333: Rename master branch

### PR DESCRIPTION
**Pull request by sdruskat**
## Pull request type

 

- Other: prepares the code base for a change in branching model

## What is the current behavior?

Issue Number: #333

The production branch is called `master`.

## What is the new behavior?

- Production branch is renamed to `main` in documentation files, GitHub workflow, template files
- Maven Gitflow Plugin is configured to accept `main` as the production branch.
-

## Does this introduce a breaking change?

No

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [x] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [x] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [x] Build (`mvn verify`) was run locally and any changes were pushed
- [x] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [x] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

### CODE REVIEW

**Comment by sdruskat** [comment]
@thomaskrause Two things we probably should do just before this PR is merged:

- Remove existing `main` branch
- Create new branch `main` from `master`

Then, after this is merged, delete branch `master`

**Review by thomaskrause — APPROVED** [review]
> Looks good to me. Should I do the manual steps (delete main, new main from master, merge PR, ...) or do you want to do the honors?

Cheers! I can do the steps and fix the changelog conflict.

**Comment by sdruskat** [comment]
> Looks good to me. Should I do the manual steps (delete main, new main from master, merge PR, ...) or do you want to do the honors?

Cheers! I can do the steps and fix the changelog conflict.

**Comment by sdruskat** [comment]
- [x] Remove existing `main` branch
- [x] Create new branch `main` from `master`
- [ ] Then, after this is merged, delete branch `master`

**Pull request merged**
