### PR TITLE
Fix most of the remaining code smells (excluding TODOs)

### PR DESCRIPTION
**Pull request by thomaskrause**
## Pull request type

 

Refactoring

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Remove unused parameter shell in CorpusStructureView#addDocument
- Replaced stream filters that use "someobject instanceof SomeClass" with method reference to isInstance.

## Does this introduce a breaking change?

N/A

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [x] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [x] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [x] Build (`mvn verify`) was run locally and any changes were pushed
- [x] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [x] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

### CODE REVIEW

**Review by sdruskat — APPROVED** [review]
LGTM, thanks!

Edit: Oopsie, still a draft ;).

**Comment by thomaskrause** [comment]
> LGTM, thanks!
> 
> Edit: Oopsie, still a draft ;).

Working on the 100% test coverage and the `ControlDecoration` in the GridEditor is still missing.

**Comment by thomaskrause** [comment]
@sdruskat The updated version is ready for review

**Review by sdruskat — APPROVED** [review]
Thanks, nice one!

**Pull request merged**
