### PR TITLE
Fix #337: Implement span creation in graph editor

### LINKED ISSUE #337: Make span creation possible in Graph Editor
**Is your feature request related to a problem? Please describe.**

While the Grid Editor is unable to create new span columns, this should be made possible in the Graph Editor with relatively little overhead.

**Describe the solution you'd like**

- The Graph Editor console gets a new command in analogy to `n`, `s`.
- `s <optional annotation 'key:val'> #<token id>...` creates a new span with the optional annotation.

**Describe alternatives you've considered**

Waiting for the Grid Editor to implement this may take longer, and this is a good solution for the meantime (and a nice feature for people preferring to use the Graph Editor).

**Additional context**

There has been a request about creating spans from potential users wanting to use Hexatomic to create a corpus.

### PR DESCRIPTION
**Pull request by stephandruskat**
## Pull request type

 

- Feature

## What is the current behavior?

Issue Number: #337 

## What is the new behavior?

- Implements span creation in graph editor:
    - Add syntax to ANTLR grammar
    - Implement handling
    - Add unit and integration tests
 - Fix #337 

## Does this introduce a breaking change?

No

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added **or** the PR is neither a bug fix nor a feature
- [x] Docs have been reviewed and added / updated if needed **or** the PR is neither a bug fix nor a feature
- [x] The *Unreleased* section in CHANGELOG.md has been amended to reflect the changes in this PR if needed
- [x] Build (`mvn verify`) was run locally and any changes were pushed
- [x] The pull request is against the correct branch (`master` for bug fixes, `develop` for new functionality)
- [x] [Dependencies and citation templates](https://github.com/hexatomic/hexatomic/tree/develop/releng/templates) have been updated where necessary **or** there are no new dependencies

---

# Checklist for maintainers

## Releases

- Do **NOT** push the green merge button on GitHub.  
Follow the latest version of the [developer/maintainer docs](https://hexatomic.github.io/hexatomic/dev/) for making releases.
- Check that license and citation information for dependencies are complete (each dependency has a folder in `/THIRD-PARTY/`).

### CODE REVIEW

**Review by bbunzeck — APPROVED** [review]
Everything works as described :)

**Comment by stephandruskat** [comment]
Hello @bbunzeck, I've realized that my SonarCloud setup was still pointing to this repository, which means that I wasn't able to run all tests. This has been fixed in https://github.com/hexatomic/hexatomic/pull/338/commits/4f41b33f92aacdd540ec154b7bacf4ba4601178e. You can check the test results once the workflows have run there.

**Comment by stephandruskat** [comment]
@bbunzeck As you can see, the tests now ran successfully: https://github.com/stephandruskat/hexatomic/actions/runs/1281800411.
If you decide to merge, I suggest you set the values for `-Dsonar.projectKey=` and `-Dsonar.organization=` back to the original values, so that the checks can also run in your repository after merge: `-Dsonar.projectKey=hexatomic_hexatomic -Dsonar.organization=hexatomic`.

**Comment by stephandruskat** [comment]
@bbunzeck As you can see, the tests now ran successfully: https://github.com/stephandruskat/hexatomic/actions/runs/1281800411.
If you decide to merge, I suggest you set the values for `-Dsonar.projectKey=` and `-Dsonar.organization=` back to the original values, so that the checks can also run in your repository after merge: `-Dsonar.projectKey=hexatomic_hexatomic -Dsonar.organization=hexatomic`.

**Comment by bbunzeck** [comment]
Thank you for your changes, now I am able to move the pull request forward.

**Pull request merged**
